version: '3.9'
name: 'prod'
services:
  backend:
    build:
      dockerfile: ./Dockerfile-prod
    container_name: backend-prod:1.0
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - AUTH_ENABLED=false
    networks:
      - network-dev
    ports:
      - "9096:8088"
networks:
  network-dev:
    external: true