version: '3.9'
name: 'prod'
services:
  prod:
    build:
      dockerfile: ./Dockerfile-prod
    container_name: prod
    restart: always
    # deploy:
    #     resources:
    #         limits:
    #           cpus: '0.50'
    #           memory: 512M
    #         reservations:
    #           cpus: '0.25'
    #           memory: 128M
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://86.48.3.202:5432/production
      - SPRING_DATASOURCE_USERNAME=prontiauto
      - SPRING_DATASOURCE_PASSWORD=prontiauto2022
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - AUTH_ENABLED=true
  
  nginx-prod:
    image: nginx:1.23-alpine
    container_name: nginx-prod
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 512M
            reservations:
              cpus: '0.25'
              memory: 128M
    ports:
      - 3200:80
      - 4200:443
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/cert
    depends_on:
      - prod