version: '3.9'
name: 'test'
services:
  test:
    build:
      dockerfile: ./Dockerfile-test
    container_name: test
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 256M
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://86.48.3.202:5432/testing
      - SPRING_DATASOURCE_USERNAME=prontiauto
      - SPRING_DATASOURCE_PASSWORD=prontiauto2022
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - AUTH_ENABLED=true

  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 512M
            reservations:
              cpus: '0.25'
              memory: 128M
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/cert
    depends_on:
      - test