version: '3.9'
name: 'dev'
services:
  dev:
    build:
      dockerfile: Dockerfile-test
    container_name: dev
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 512M
            reservations:
              cpus: '0.25'
              memory: 128M
    depends_on:
      - db
    ports:
      - "9096:8082"
    networks:
      - network-dev
networks:
  network-dev:
    external: true

  
