version: '3.9'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PIPj0SMJKGDVw3I
      - POSTGRES_DB=prontiauto
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - network-dev

networks:
  network-dev:
    external: true